### PR TITLE
Add codespell support (config, workflow to detect/not fix) and make it fix few typos

### PR DESCRIPTION
**Pull request by yarikoptic**
Blame @Remi-Gau

More about codespell: https://github.com/codespell-project/codespell .

I personally introduced it to dozens if not hundreds of projects already and so far only positive feedback.

CI workflow has 'permissions' set only to 'read' so also should be safe.

### CODE REVIEW

**Comment by paquiteau** [comment]
Hi thanks for the PR 
Codespell will be a great addition indeed.

Any reason to not put it inside the linter workflow (with black and ruff) ? 

Otherwise LGTM :)

**Comment by Remi-Gau** [comment]
> Any reason to not put it inside the linter workflow (with black and ruff) ?

That's because the spell of @yarikoptic sets things in separate workflow by default.

If I am not mistaken this whole PR was created by casting the spell with a single command on his terminal.

**Comment by Remi-Gau** [comment]
I can take care to integrate into the linting workflow in a follow up PR.

**Comment by yarikoptic** [comment]
> If I am not mistaken this whole PR was created by casting the spell with a single command on his terminal.

Correct. It is this little helper:
- https://github.com/yarikoptic/improveit/blob/main/codespellit

happen you would like to cast spells too ;)  but if you are really into casting, check those out https://github.com/datalad/screencaster which could make you appear really like a magician while giving life demos -- "typing" commands very fast and without mistakes, while still potentially interactively working in that terminal.  @adswa can attest that it brings awe to the audience ;)

**Comment by Remi-Gau** [comment]
if this conversation continues I am going to create a bunch of alias that are harry potter based:

I'll start

accio='git pull'

**Comment by paquiteau** [comment]
Awesome stuff @yarikoptic you truly are a wizard with more mana than me 😅 

Let's get done with this though 😊

**Pull request merged**
