### PR TITLE
[MAINT] run tests with all python >=3.9

### PR DESCRIPTION
**Pull request by Remi-Gau**
- drop python<3.8
- support all python >= 3.9: test in CI

### CODE REVIEW

**Comment by Remi-Gau** [comment]
will rebase on main once #5 is merged

**Comment by tsalo** [comment]
lol you figured out the problem so much faster than me. I think the type annotations with `|` require at least Python 3.10 though.

**Comment by Remi-Gau** [comment]
na adding `from __future__ import annotations` at the top of the module should be fine

**Comment by tsalo** [comment]
Oh cool! I'll put that in my PR then.

**Review by paquiteau — APPROVED** [review]

**Pull request merged**
