### PR TITLE
Address linting and test errors

### PR DESCRIPTION
**Pull request by tsalo**
Apologies for the unsolicited PR. I mostly just wanted to see why tests were failing in the last commit, but the logs were expired.

### CODE REVIEW

**Comment by paquiteau** [comment]
Hi, no worries, Any help is welcome!

**Comment by tsalo** [comment]
It looks like the linter-check job runs black, but style issues flagged by that step don't affect the job's status? I.e., it's passing now, but if I navigate to the Black Check step in the CI log there are a bunch of things black would change.

**Comment by Remi-Gau** [comment]
@tsalo: aren't you afraid that adding the word typo in the title of the PR may summon the codespell demon? (AKA @yarikoptic) 😜

**Comment by tsalo** [comment]
oohhh good point! 😄 Plus this is mostly about getting the linter and tests passing at this point anyway

**Comment by Remi-Gau** [comment]
yay: all green !

**Review by paquiteau — APPROVED** [review]

**Comment by paquiteau** [comment]
Thank you for the clean up! I guess we have a good starting point to built upon :)

**Comment by Remi-Gau** [comment]
is that a flaky test ?

**Comment by Remi-Gau** [comment]
I can reliably get it locally.

**Comment by Remi-Gau** [comment]
weird: the fail happens on #7 on python 3.8 but not on #6 that does not run 3.8 but I get the fail locally with python 3.12...

**Comment by Remi-Gau** [comment]
OK my bad: when running locally in proper virtual environment (and not my usual conda 'ecosystem' - larger and meaner than an environment), everything is OK.

So I would try merging #6 to stop supporting py3.8 and get rid of the error.

**Comment by tsalo** [comment]
Sounds good to me!

**Comment by yarikoptic** [comment]
> @tsalo: aren't you afraid that adding the word typo in the title of the PR may summon the codespell demon? (AKA @yarikoptic) 😜

image

- https://github.com/paquiteau/patch-denoising/pull/12

**Pull request merged**
